### ISSUE TITLE
Does the code work?

### ISSUE THREAD

**Issue by alex9099** [ParkerMc/VR#1]
Hi, I want to do something similar to what you did, and i found this repository, is your code working?

**Comment by ParkerMc** [comment]
It works for what is was programmed and right now that is not much. There are 3 parts the program, the app, and the open vr driver. Right now the program is only a utp echo server. The app right now only shows giro scenes and the driver is only the sample null driver from the open vr repo. I found out after I started working on it that I need to upgrade my computer and I still have not gotten around to that. Feel free to take my code and work on it in your own repo or here I don't care. Just let me know what you end up doing so that once I upgrade my computer I can help. 

P.s. All of the code I used Qt creator for you have to use that for that app and the program if you use my code.

**Comment by alex9099** [comment]
Cool, but there is no video streaming yet, right? i cant understand how that is suposed to do :/

For some reason the null driver on linux steamvr gives me error 306, about some ipc compositor :/

**Comment by ParkerMc** [comment]
Yeah no streaming yet. I know how it should work I will type it up when
I get the time to. 

The 306 is either a driver or some other issue you will have to look in
the logs. 

If you want more help I would rather take it out of the issue section if
you could just move here that would be better.
https://gitter.im/ParkerMc-VR/
